global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    metrics_path: /api/metrics # Specify the path separately
    static_configs:
      - targets:
          - "192.168.8.100:3000" # Host and port only
